# Generated by Django 5.0.4 on 2024-05-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("article", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepost",
            name="total_views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
